HigherEdu/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from ctm_admin.subapps.ads.views import get_new_ad_refresh

fav_icon = RedirectView.as_view(url='/static/icons/favicon.ico', permanent=True)

urlpatterns = [
    path('db-admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('dashboard.urls')),
    path('admin/', include('ctm_admin.urls')),
    path('ads/get_new_refresh',get_new_ad_refresh,name="ads-refresh"),
    path('utils/', include('utils.urls')),
    path('study/', include('applies.urls')),
    re_path(r'^favicon\.ico$', fav_icon),
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ctm_admin/subapps/ads/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # Ad Base
    path('ads-list-view/', AdminADS.as_view(), name='ctm_admin-ads-list-view'),
    path('create/', AdsCreateView.as_view(), name='ctm_admin-ads_create'),
    path('<uuid:uuid>/', AdsDetailView.as_view(), name='ctm_admin-ads_detail'),
    path('<uuid:uuid>/edit/', AdsEditView.as_view(), name='ctm_admin-ads_edit'),
    path('<uuid:uuid>/delete/', AdsDeleteView.as_view(), name='ctm_admin-ads_delete'),

    # Ad Size
    path('ads_sizes/', AdsSize_List_Create.as_view(), name='ctm_admin-ads_size_list_create'),
    path('ads_sizes/<int:pk>/delete/', AdsSizeDeleteView.as_view(), name='ctm_admin-ads_size_delete'),
]

ctm_admin/urls.py
from django.urls import path,include
from .views import *
from .contacts_views import *

urlpatterns = [
    path("", Main, name="ctm_admin-main"),

    # User Type
    path('usertypes/', UserTypeListView.as_view(), name='ctm_admin-usertype_list'),
    path('usertypes/create/', UserTypeCreateView.as_view(), name='ctm_admin-usertype_create'),
    path('usertypes/<int:pk>/', UserTypeDetailView.as_view(), name='ctm_admin-usertype_detail'),
    path('usertypes/<int:pk>/edit/', UserTypeUpdateView.as_view(), name='ctm_admin-usertype_edit'),
    path('usertypes/<int:pk>/delete/', UserTypeDeleteView.as_view(), name='ctm_admin-usertype_delete'),

    # Users
    path("create-users/", CreateUser.as_view(), name="ctm_admin-create-users"),
    path("all-users/", UsersListview.as_view(), name="ctm_admin-all-users"),

    # Staff Users
    path("staff-users/", StaffUserList.as_view(), name="ctm_admin-staff-users"),
    path('staff-users/<int:pk>/', StaffUserDetails.as_view(), name='ctm_admin-staff-users-detail'),
    path('staff-users/<int:pk>/edit/', StaffUserUpdateView.as_view(), name='ctm_admin-staff-users-edit'),
    path('staff-users/<int:pk>/delete/', StaffUserDeleteView.as_view(), name='ctm_admin-staff-users-delete'),
    path('staff-users/<int:pk>/change_password/', StaffUserChangePassword.as_view(), name='ctm_admin-staff-users-change_password'),

    # Contact Messages
    path("contactus/", ContactUsListview.as_view(), name="ctm_admin-contactus_list"),
    path('contactus/<int:pk>/', ContactUsDetailView.as_view(), name='ctm_admin-contactus_detail'),
    path('contactus/<int:pk>/edit/', ContactUsUpdateView.as_view(), name='ctm_admin-contactus_edit'),
    path('contactus/<int:pk>/delete/', ContactUsDeleteView.as_view(), name='ctm_admin-contactus_delete'),

    # Data Export
    path("export-excel-all-users/", UserDataExportExcel, name="ctm_admin-export-excel-all-users"),
    path("export-csv-all-users/", UserDataExportCsv, name="ctm_admin-export-csv-all-users"),

    # ADS System
    path("ads/",include('ctm_admin.subapps.ads.urls')),

    # Applies Courses
    path("applies/",include('ctm_admin.subapps.applies_adm.urls')),
]

utils/urls.py
from django.urls import path, include
from .views import *
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('validate-email', csrf_exempt(EmailValidation.as_view()), name='utils-validate-email'),
    path('college-list', csrf_exempt(CollegeList.as_view()), name='utils-college-list'),
    path('country-list', csrf_exempt(CountryList.as_view()), name='utils-country-list'),
    path('country-list-world', csrf_exempt(CollegeListWorld.as_view()), name='utils-country-list-world'),
    path('terms-and-conditions', TermsConds, name='utils-terms-conds'),
    path('contact-us', ContactUsForm.as_view(), name='utils-contact-us'),
]

ctm_admin/models.py
from django.db import models
from django.contrib.auth.models import Permission

class CtmAdminPermission(models.Model):
    class Meta:
        permissions = [
            ("view_dashboard", "Can view the dashboard"),
        ]

ctm_admin/subapps/ads/models.py
from django.db import models
import uuid

class AdsSize(models.Model):
    width = models.CharField(max_length=100,null=True,blank=True)
    height = models.CharField(max_length=100,null=True,blank=True)
    
    def __str__(self):
        return f"{self.width}x{self.height}"

class AdsBase(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=240,null=True,blank=True)
    url = models.URLField(null=True,blank=True)
    size = models.ForeignKey(AdsSize,on_delete=models.CASCADE)
    forward_url = models.URLField(null=True,blank=True)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return f"{self.title} - {self.size}"

ctm_admin/subapps/applies_adm/models.py
from django.db import models

# Create your models here.

utils/models.py
from django.db import models

class ContactUs(models.Model):
    name = models.CharField(max_length=255,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    phone_no = models.CharField(max_length=255,null=True,blank=True)
    message = models.TextField(null=True,blank=True)
    by_login_user = models.BooleanField(default=False)
    is_replyed = models.BooleanField(default=False)
    is_ignored = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.email}"

ctm_admin/forms.py
from django import forms
from utils.models import ContactUs
from accounts.models import UserType
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import Permission

User = get_user_model()

class ContactUs_Msg_Form(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'phone_no', 'message', 'by_login_user','is_replyed','is_ignored']

    def __init__(self, *args, **kwargs):
        super(ContactUs_Msg_Form, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['phone_no'].widget.attrs['readonly'] = True
        self.fields['message'].widget.attrs['readonly'] = True

    def clean_name(self):
        if self.instance and self.cleaned_data['name'] != self.instance.name:
            raise forms.ValidationError("Name cannot be edited.")
        return self.cleaned_data['name']

    def clean_email(self):
        if self.instance and self.cleaned_data['email'] != self.instance.email:
            raise forms.ValidationError("Email cannot be edited.")
        return self.cleaned_data['email']

    def clean_phone_no(self):
        if self.instance and self.cleaned_data['phone_no'] != self.instance.phone_no:
            raise forms.ValidationError("Phone number cannot be edited.")
        return self.cleaned_data['phone_no']
    
    def clean_message(self):
        if self.instance and self.cleaned_data['message'] != self.instance.message:
            raise forms.ValidationError("message cannot be edited.")
        return self.cleaned_data['message']

class UserTypeForm(forms.ModelForm):
    class Meta:
        model = UserType
        fields = ['name', 'permissions']

    def __init__(self, *args, **kwargs):
        super(UserTypeForm, self).__init__(*args, **kwargs)
        allowed_apps = ['accounts', 'ads','utils','ctm_admin','applies']
        app_permissions = Permission.objects.filter(content_type__app_label__in=allowed_apps)
        permission_choices = [(perm.codename, f'{perm.content_type.app_label} - {perm.name} Data',perm.id) for perm in app_permissions]
        self.fields['permissions'].choices = permission_choices
        self.fields['permissions'].help_text = 'Select Multiple permissions to be Granted'
        self.fields['name'].widget.attrs['placeholder'] = 'Enter Name of UserType (ex: SubAdmin..)'
        self.fields['permissions'].widget.attrs['placeholder'] = 'Select all the permissions Granted'
    
class UserForm(UserCreationForm):
    user_type = forms.ModelChoiceField(queryset=UserType.objects.all(), required=False)
    class Meta:
        model = User
        fields = ['email','password1','password2','first_name','last_name','is_staff','user_type']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.user_type = self.cleaned_data['user_type']
            user.save()
        return user

class UserUpdateForm(forms.ModelForm):
    user_type = forms.ModelChoiceField(queryset=UserType.objects.all(), required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'is_staff', 'user_type']

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.user_type = self.cleaned_data['user_type']
            user.save()
        return user

ctm_admin/subapps/ads/forms.py
from django import forms
from .models import AdsBase,AdsSize

class AdsBaseForm(forms.ModelForm):
    class Meta:
        model = AdsBase
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(AdsBaseForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = 'Enter Title'
        self.fields['url'].widget.attrs['placeholder'] = 'Enter Ad Image URL'
        self.fields['forward_url'].widget.attrs['placeholder'] = 'Enter Forward URL'

class AdsSizeForm(forms.ModelForm):
    class Meta:
        model = AdsSize
        fields = ['width', 'height']

    def __init__(self, *args, **kwargs):
        super(AdsSizeForm, self).__init__(*args, **kwargs)
        self.fields['width'].widget.attrs['placeholder'] = 'Enter Width of New Ads'
        self.fields['height'].widget.attrs['placeholder'] = 'Enter Height of New Ads'

ctm_admin/subapps/ads/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse,reverse_lazy
from ctm_admin.subapps.ads.utils import GetAds
from django.views import View
from django.views.generic import ListView,UpdateView,DetailView,DeleteView,CreateView
from ctm_admin.mixins import CheckAdminMixin
from .models import AdsBase,AdsSize
from .forms import AdsBaseForm,AdsSizeForm
from django.shortcuts import render,redirect

def get_new_ad_refresh(request):
    size = request.GET.get('size', '300x200')
    url, forward, H, W = GetAds(size)
    html_send = render_to_string('ads_snippets/ads_refresh.html', {'url': url, 'forward': forward, 'H': H, 'W': W, 'size':size})
    return JsonResponse({'new_ad_html': html_send})

# Ads Crud

class AdminADS(CheckAdminMixin,ListView):
    model = AdsBase
    template_name = 'ctm_admin/ads/ads_list-view.html'
    model_permissions = {
        'ads': ['view_adsbase']
    }

class AdsDetailView(CheckAdminMixin,DetailView):
    model = AdsBase
    template_name = 'ctm_admin/ads/ads_detail.html'
    context_object_name = 'ad'
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    model_permissions = {
        'ads': ['view_adsbase']
    }

class AdsEditView(CheckAdminMixin,UpdateView):
    model = AdsBase
    form_class = AdsBaseForm
    template_name = 'ctm_admin/ads/ads_edit.html'
    context_object_name = 'ad'
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    model_permissions = {
        'ads': ['change_adsbase']
    }

    def get_success_url(self):
        return reverse_lazy('ctm_admin-ads_detail', kwargs={'uuid': self.object.uuid})

class AdsDeleteView(CheckAdminMixin,DeleteView):
    model = AdsBase
    template_name = 'ctm_admin/ads/ads_confirm_delete.html'
    context_object_name = 'ad'
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    success_url = reverse_lazy('ctm_admin-ads-list-view')
    model_permissions = {
        'ads': ['delete_adsbase']
    }

class AdsCreateView(CheckAdminMixin,CreateView):
    model = AdsBase
    form_class = AdsBaseForm
    template_name = 'ctm_admin/ads/ads_create.html'
    success_url = reverse_lazy('ctm_admin-ads-list-view')
    model_permissions = {
        'ads': ['add_adsbase']
    }

# Ad Size Crud views
class AdsSize_List_Create(CheckAdminMixin,View):
    template_name = 'ctm_admin/ads/ads_size_list_create.html'
    model_permissions = {
        'ads': ['add_adssize','view_adssize']
    }

    def get(self, request, *args, **kwargs):
        sizes = AdsSize.objects.all()
        form = AdsSizeForm()
        return render(request, self.template_name, {'sizes': sizes, 'form': form})

    def post(self, request, *args, **kwargs):
        form = AdsSizeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ctm_admin-ads_size_list_create')
        else:
            sizes = AdsSize.objects.all()
            return render(request, self.template_name, {'sizes': sizes, 'form': form})

class AdsSizeDeleteView(CheckAdminMixin,DeleteView):
    model = AdsSize
    template_name = 'ctm_admin/ads/ads_size_confirm_delete.html'
    context_object_name = 'size'
    success_url = reverse_lazy('ctm_admin-ads_size_list_create')
    model_permissions = {
        'ads': ['delete_adssize']
    }

templates/ctm_admin/contacts_msg/contacts_list.html
{% extends 'ctm_admin/base/index.html' %}

{% block title %}
Contact Messages | {{site_name}} Admin
{% endblock title %}

{% block content %}
<h2>Contact Messages</h2>
<div class="row mb-2">
</div>
<div class="card py-1 px-1">
    <div class="card-body p-1">
        <div class="table-responsive">
            <div class="row">
                <div class="col-md-12 ctm_table">
                    <table class="table table-hover table-sm">
                        <thead class="table-secondary">
                            <tr>
                                <th class="text-default">Name</th>
                                <th class="text-default">Email</th>
                                <th class="text-default">Mobile No</th>
                                <th class="text-default">Message</th>
                                <th class="text-default">Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in contacts %}
                            <tr>
                                <td>{{ i.name }}</td>
                                <td>{{ i.email }}</td>
                                <td>{{ i.phone_no }}</td>
                                <td>{{i.message}}</td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" data-bs-boundary="window" aria-expanded="false">
                                            Select an option
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="{% url 'ctm_admin-contactus_detail' i.pk %}"><i class="fa-solid fa-eye"></i> View Details</a></li>
                                            <li><a class="dropdown-item" href="{% url 'ctm_admin-contactus_edit' i.pk %}"><i class="fa-solid fa-pen-to-square"></i> Edit</a></li>
                                            <li><a class="dropdown-item" href="{% url 'ctm_admin-contactus_delete' i.pk %}" onclick="return confirm('Are you sure you want to delete this message?')"><i class="fa-solid fa-trash"></i> Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script>
    $(document).ready(function() {
        $('.table').DataTable( {
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ]
        } );
    } );
</script>
<script>
    $('.table-responsive').on('show.bs.dropdown', function () {
        $('.table-responsive').css( "overflow", "inherit" );
   });
   
   $('.table-responsive').on('hide.bs.dropdown', function () {
        $('.table-responsive').css( "overflow", "auto" );
   })
</script>
{% endblock scripts %}


{% block styles %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
<style>
    .tb-date{
        min-width: 120px;
    }
    .ctm_table .form-control{
        margin-top: 5px;
        margin-right: 5px;
    }
    .ctm_table .pagination{
        margin-right: 5px;
    }
    .ctm_table .form-select{
        margin-top: 5px;
    }
</style>
{% endblock styles %}

templates/ctm_admin/contacts_msg/contactus_confirm_delete.html
{% extends 'ctm_admin/base/index.html' %}

{% block title %}
Contact Messages Delete | {{site_name}} Admin
{% endblock title %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header py-2">
        <h2>Delete Contact Us Message</h2>
      </div>
      <div class="card-body pt-1">
        <p>Are you sure you want to delete "<span class="fw-bold">{{ contact.name }} - {{ contact.email }}</span>" contact ?</p>
        <form method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Yes, delete</button>
          <a href="{% url 'ctm_admin-contactus_detail' pk=contact.pk %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/ctm_admin/contacts_msg/contactus_detail.html
{% extends 'ctm_admin/base/index.html' %}

{% block title %}
Contact Messages Details | {{site_name}} Admin
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header py-2">
                <h3>Contact Us Message Details</h3>
            </div>
            <div class="card-body pt-1">
                <p><span class="fw-bold">Name:</span> {{ contact.name }}</p>
                <p><span class="fw-bold">Email:</span> {{ contact.email }}</p>
                <p><span class="fw-bold">Phone No:</span>
                    <input disabled readonly type="tel" class="form-control" id="inputmobile_no" value="{{ contact.phone_no }}"></p>
                <p><span class="fw-bold">Message:</span> {{ contact.message }}</p>
                <div class="mt-2 form-check form-switch">
                    <label for="id_contactus_reg_user" class="fw-bold">Is By Registered User</label>
                    <input readonly disabled type="checkbox" id="id_contactus_reg_user" class="form-check-input" {% if contact.by_login_user == True %}checked{% endif %}>
                </div>
                <div class="mt-2 form-check form-switch">
                    <label for="id_contactus_replyed" class="fw-bold">Is Replyed</label>
                    <input readonly disabled type="checkbox" id="id_contactus_replyed" class="form-check-input" {% if contact.is_replyed == True %}checked{% endif %}>
                </div>
                <div class="mt-2 mb-2 form-check form-switch">
                    <label for="id_contactus_ignored" class="fw-bold">Is Ignored</label>
                    <input readonly disabled type="checkbox" id="id_contactus_ignored" class="form-check-input" {% if contact.is_ignored == True %}checked{% endif %}>
                </div>
                <p class="card-text m-0"><span class="fw-bold">Last Updated:</span> {{ contact.last_updated }}</p>
                <p class="card-text m-0"><span class="fw-bold">Created at:</span> {{ contact.created_at }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'ctm_admin-contactus_edit' pk=contact.pk %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'ctm_admin-contactus_delete' pk=contact.pk %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this message?')">Delete</a>
                <a href="{% url 'ctm_admin-contactus_list' %}" class="btn btn-secondary"><i class="fa-solid fa-arrow-left"></i>&nbsp;Back to List</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/intlTelInput.min.js"></script>
<script>
    const input = document.querySelector("#inputmobile_no");
    window.intlTelInput(input, {
        separateDialCode: true,
        hiddenInput: "phone_no",
        nationalMode: false, 
        preferredCountries: ["in"],
        initialCountry: "auto",
        geoIpLookup: callback => {
            fetch("https://ipapi.co/json")
              .then(res => res.json())
              .then(data => callback(data.country_code))
              .catch(() => callback("in"));
        },
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js",
      });
</script>
{% endblock scripts %}


{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/css/intlTelInput.css">
{% endblock styles %}

templates/ctm_admin/contacts_msg/contactus_update_form.html
{% extends 'ctm_admin/base/index.html' %}

{% block title %}
Contact Messages Details | {{site_name}} Admin
{% endblock title %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header py-2">
        <h3>Edit Contact Us Message</h3>
      </div>
      <div class="card-body pt-1">
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                    <div class="mt-2 form-check form-switch">
                      {{field.label_tag}}
                      <span><small>{{field.help_text}}</small></span>
                      <input {% if field.field.widget.attrs.readonly %} readonly {% endif %} type="{{field.field.widget.input_type}}" id="id_{{field.name}}" name="{{field.name}}" class="form-check-input" {% if field.value == True %}checked{% endif %}>
                        {% if field.errors %}
                        <div class="alert alert-danger m-0 p-0">{{field.errors}}</div>
                        {% endif %}
                    </div>
                    {% else %}
                    <div class="mt-2 form-group">
                        {{field.label_tag}}
                        <input {% if field.field.widget.attrs.readonly %} readonly {% endif %} required type="{{field.field.widget.input_type}}" value="{{field.value}}" id="id_{{field.name}}" name="{{field.name}}" class="form-control" {% if field.field.widget.attrs.placeholder %} placeholder="{{ field.field.widget.attrs.placeholder }}"{% endif %}>
                        <span><small>{{field.help_text}}</small></span>
                        {% if field.errors %}
                        <div class="alert alert-danger m-0 p-0">{{field.errors}}</div>
                        {% endif %}
                    </div>
                    {% endif %}
                    {% endfor %}
          <button type="submit" class="btn btn-success w-100 my-2">Save</button>
        </form>
        <a href="{% url 'ctm_admin-contactus_list' %}" class="btn btn-secondary w-100">Cancel</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/intlTelInput.min.js"></script>
<script>
    const input = document.querySelector("#id_phone_no");
    window.intlTelInput(input, {
        separateDialCode: true,
        hiddenInput: "phone_no",
        nationalMode: false, 
        preferredCountries: ["in"],
        initialCountry: "auto",
        geoIpLookup: callback => {
            fetch("https://ipapi.co/json")
              .then(res => res.json())
              .then(data => callback(data.country_code))
              .catch(() => callback("in"));
        },
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js",
      });
</script>
{% endblock scripts %}


{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/css/intlTelInput.css">
{% endblock styles %}